// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package fetcher

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewFetcher creates a new instance of Fetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFetcher[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Fetcher[T] {
	mock := &Fetcher[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher[T any] struct {
	mock.Mock
}

type Fetcher_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *Fetcher[T]) EXPECT() *Fetcher_Expecter[T] {
	return &Fetcher_Expecter[T]{mock: &_m.Mock}
}

// Fetch provides a mock function for the type Fetcher
func (_mock *Fetcher[T]) Fetch(ctx context.Context, keys []string) ([]T, error) {
	ret := _mock.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]T, error)); ok {
		return returnFunc(ctx, keys)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []T); ok {
		r0 = returnFunc(ctx, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, keys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Fetcher_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type Fetcher_Fetch_Call[T any] struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
func (_e *Fetcher_Expecter[T]) Fetch(ctx interface{}, keys interface{}) *Fetcher_Fetch_Call[T] {
	return &Fetcher_Fetch_Call[T]{Call: _e.mock.On("Fetch", ctx, keys)}
}

func (_c *Fetcher_Fetch_Call[T]) Run(run func(ctx context.Context, keys []string)) *Fetcher_Fetch_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Fetcher_Fetch_Call[T]) Return(vs []T, err error) *Fetcher_Fetch_Call[T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *Fetcher_Fetch_Call[T]) RunAndReturn(run func(ctx context.Context, keys []string) ([]T, error)) *Fetcher_Fetch_Call[T] {
	_c.Call.Return(run)
	return _c
}
